name: jobs examples

on:
  push
jobs:
  job1:
    runs-on: ubuntu-lates
    steps:
      -  name: step do job1
         run: echo Hello, World! job1.
  job2:
    runs-on: ubuntu-latest
    steps:
      -  name: step dp job2
         run: echo Hello, World! Job2.
